+incdir+../../src/globals/
+incdir+../../src/hvlTop/spiMaster/spiMasterSequences/
+incdir+../../src/hvlTop/spiMaster/
+incdir+../../src/hdlTop/masterAgentBFM/ 
+incdir+../../src/hvlTop/spiEnv/virtualSequencer/
+incdir+../../src/hvlTop/tb/virtualSequences/
+incdir+../../src/hvlTop/spiEnv/
+incdir+../../src/hvlTop/spiSlave/
+incdir+../../src/hvlTop/spiSlave/spiSlaveSequences/
+incdir+../../src/hvlTop/tb/test/
+incdir+../../src/hdlTop/slaveAgentBFM/
+incdir+../../src/hdlTop/spiInterface/
../../src/globals/SpiGlobalsPkg.sv
../../src/hvlTop/spiMaster/SpiMasterPkg.sv
../../src/hvlTop/spiSlave/SpiSlavePkg.sv
../../src/hvlTop/spiMaster/spiMasterSequences/SpiMasterSeqPkg.sv
../../src/hvlTop/spiSlave/spiSlaveSequences/SpiSlaveSeqPkg.sv
../../src/hvlTop/spiEnv/SpiEnvPkg.sv
../../src/hvlTop/tb/virtualSequences/SpiVirtualSeqPkg.sv
../../src/hvlTop/tb/test/SpiTestPkg.sv
../../src/hdlTop/spiInterface/SpiInterface.sv
../../src/hdlTop/masterAgentBFM/SpiMasterDriverBFM.sv
../../src/hdlTop/masterAgentBFM/SpiMasterMonitorBFM.sv
../../src/hdlTop/masterAgentBFM/SpiMasterAgentBFM.sv
../../src/hdlTop/slaveAgentBFM/SpiSlaveDriverBFM.sv
../../src/hdlTop/slaveAgentBFM/SpiSlaveMonitorBFM.sv
../../src/hdlTop/slaveAgentBFM/SpiSlaveAgentBFM.sv
../../src/hdlTop/SpiHdlTop.sv
../../src/hvlTop/SpiHvlTop.sv
../../src/hdlTop/SpiMasterAssertions.sv
../../src/hdlTop/SpiSlaveAssertions.sv
